### ISSUE TITLE
Yadda 0.13.0 breaks Moonraker

### ISSUE THREAD

**Issue by cressie176** [LateRoomsGroup/moonraker#28]
I made some breaking changes in Yadda 0.13.0 around annotation handling and thought I check whether it caused Moonraker any problems. Unfortunately it does. https://github.com/acuminous/moonraker/commit/bdd40368c76f21e650ab247bc189abe010eb2695 is my commit which fixes the easy ones, but the basic example still fails.

```
/Users/steve/Development/acuminous/moonraker/node_modules/yadda/lib/plugins/mocha/BasePlugin.js:80
        return $(annotations && annotations.keys()).find(function(key) {
                                            ^
TypeError: Object #<Object> has no method 'keys'
  at has_annotation (/Users/steve/Development/acuminous/moonraker/node_modules/yadda/lib/plugins/mocha/BasePlugin.js:80:45)
  at getDescribe (/Users/steve/Development/acuminous/moonraker/node_modules/yadda/lib/plugins/mocha/BasePlugin.js:73:13)
  at describe (/Users/steve/Development/acuminous/moonraker/node_modules/yadda/lib/plugins/mocha/BasePlugin.js:46:25)
  at /Users/steve/Development/acuminous/moonraker/node_modules/yadda/lib/plugins/mocha/BasePlugin.js:41:13
  at Array.each (/Users/steve/Development/acuminous/moonraker/node_modules/yadda/lib/Array.js:63:22)
  at Array.each (/Users/steve/Development/acuminous/moonraker/node_modules/yadda/lib/fn.js:27:23)
  at features (/Users/steve/Development/acuminous/moonraker/node_modules/yadda/lib/plugins/mocha/BasePlugin.js:40:21)
  at Object.<anonymous> (/Users/steve/Development/acuminous/moonraker/lib/env/yadda.js:16:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at /Users/steve/Development/acuminous/moonraker/node_modules/mocha/lib/mocha.js:185:27
  at Array.forEach (native)
  at Mocha.loadFiles (/Users/steve/Development/acuminous/moonraker/node_modules/mocha/lib/mocha.js:182:14)
  at Mocha.run (/Users/steve/Development/acuminous/moonraker/node_modules/mocha/lib/mocha.js:394:31)
  at process.<anonymous> (/Users/steve/Development/acuminous/moonraker/lib/env/mocha.js:26:11)
  at process.emit (events.js:98:17)
  at handleMessage (child_process.js:322:10)
  at Pipe.channel.onread (child_process.js:349:11)
```

I think [this](https://github.com/acuminous/moonraker/blob/master/bin/moonraker.js#L18) line is the problem. My change was to convert the annotations map into a class. My guess is that when the annotations were a simple object they serialised fine, but now that they're a private member of a closure they don't.

Assuming I'm correct, I'm happy to revert my change in Yadda. Being able to send features to different threads seems pretty core to Moonraker and I don't want to break that.

Thoughts?

**Comment by cressie176** [comment]
I've changed Yadda back so that annotations are exported as simple objects again. Moonraker example works fine with v0.13.1.
